services:
  # postgres:
  #   image: postgres:latest
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=petclinic
  #     - POSTGRES_USER=petclinic
  #     - POSTGRES_DB=petclinic
  petclinic:
    image: spring.petclinic:${CONTAINER_VESION:-latest}
    container_name: petclinic
    build: ./
    environment:
      - SPRING_PROFILES_ACTIVE = ${SPRING_PROFILES_ACTIVE:-default}
      - SPRING_DATASOURCE_URL = ${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME = ${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD = ${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_URL = ${POSTGRES_URL}
      - POSTGRES_USER = ${POSTGRES_PASS}
      - POSTGRES_URL = ${POSTGRES_URL}
    ports:
      - "8080:8080"

